finance/urls.py
from django.urls import path
from finance.apps import FinanceConfig
import finance.views as vw

app_name = FinanceConfig.name
urlpatterns = [
    path('category', vw.category, name='category'),
    path('category/<int:boardID>', vw.category, name='category'),
    path('year', vw.year, name='year'),
]

general/urls.py
from django.urls import path
from general.apps import GeneralConfig
import general.views as vw

app_name = GeneralConfig.name
urlpatterns = [
    path('', vw.mainView, name='mainView'),
    path('<int:boardID>', vw.mainView, name='mainView'),
    path('board', vw.board, name='board'),
    path('board/<int:boardID>', vw.board, name='boardid'),
]

mantis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('mantis/', include('general.urls', namespace='general')),
    path('finance/', include('finance.urls', namespace='finance')),
]

finance/models.py
from django.contrib.auth.models import User
from django.db import models
from general.models import Board

class ExpanceCategory(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    caption = models.CharField(max_length=20)

    def __str__(self):
        return self.caption
    
    def escaped_caption(self):
        return self.caption.replace("'", "\\'")

class ExpanceRecord(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    category = models.ForeignKey(ExpanceCategory, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    value = models.IntegerField()

general/models.py
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models

class Board(models.Model):
    class BoardType(models.IntegerChoices):
        Tasks = 0, 'Tasks'
        Finance = 1, 'Finance'
    
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    caption = models.CharField(max_length=20)
    type = models.IntegerField(choices=BoardType.choices)

    def __str__(self):
        return self.caption
    
    def get_url(self):
        return reverse("general:boardid", args=[str(self.id)])

finance/views.py
import json
from django.http.response import JsonResponse
from django.db.models import Sum
from django.shortcuts import render
from general.datehelp import month_range, day_range
from .models import ExpanceCategory, ExpanceRecord

def __tryint(val: str) -> int:
    try:
        return int(val)
    except:
        return None

def category(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        category = ExpanceCategory(
            id = data['id'] if str(data['id']).isnumeric() else None,
            board_id = data['board_id'],
            caption = data['caption'])
        category.save()
        return JsonResponse({'success': True, 'errorMsg': ''})
    if request.method == 'GET':
        boardID = __tryint(request.GET.get('boardID', ''))
        if not boardID:
            raise NotImplementedError('Not implemented')
        else:
            categories = ExpanceCategory.objects.filter(board_id=boardID).order_by('id')
            res = {'categories': categories}
            return render(request, 'finance/categories.html', res)
    raise NotImplementedError('Not implemented')

def year(request):
    boardID = __tryint(request.GET.get('boardID', ''))
    year = __tryint(request.GET.get('year', ''))
    cat_totals = []
    m_totals = []
    categories = ExpanceCategory.objects.filter(board_id=boardID).order_by('id')
    for category in categories:
        cat_totals.append({'sum': ExpanceRecord.objects.filter(board_id=boardID, category_id=category.id,
            date__gte=f'{year}-1-1', date__lte=f'{year}-12-31').aggregate(Sum('value'))['value__sum'] or 0})
    for month in month_range(year):
        m_cat = []
        for category in categories:
            m_cat.append({'sum': ExpanceRecord.objects.filter(board_id=boardID, category_id=category.id,
                date__gte=month.start, date__lte=month.end).aggregate(Sum('value'))['value__sum'] or 0})
        
        d_totals = []
        for day in day_range(year, month.number):
            d_cat = []
            for category in categories:
                d_cat.append({'sum': ExpanceRecord.objects.filter(board_id=boardID, category_id=category.id,
                    date=f'{year}-{month.number}-{day}').aggregate(Sum('value'))['value__sum'] or 0})
            d_totals.append({'categories': d_cat, 'caption': day})
        
        m_totals.append({'categories': m_cat, 'caption': month.caption, 'days': d_totals})

    res = {'year': year, 'year_categories': cat_totals, 'months': m_totals}
    return render(request, 'finance/year.html', res)

general/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from .models import Board

import json

def mainView(request, boardID=None):
    board_types = Board.BoardType.choices
    #res = {'board_types': board_types, 'debugMode': 1 if settings.DEBUG else 0 }
    res = {'board_types': board_types, 'debugMode': 1}
    return render(request, 'general/base.html', res)

def board(request, boardID=None):
    if request.method == 'POST':
        data = json.loads(request.body)
        board = Board(
            id = data['id'] if str(data['id']).isnumeric() else None,
            caption = data['caption'],
            type = data['type'],
            owner = request.user)
        board.save()
        return JsonResponse({'success': True, 'errorMsg': ''})
    elif request.method == 'GET':
        if not boardID:
            if request.user.is_authenticated:
                all_boards = Board.objects.filter(owner=request.user)
                res = {'boards': all_boards}
            else:
                res = {}
            # if request.user.id == 3:  # TODO: Implement propper board shearing
            #    sheared_board = Board.objects.filter(id = 3)
            #    all_boards = all_boards.union(sheared_board)
            return render(request, 'general/board-list.html', res)
        else:
            board = Board.objects.get(id=boardID)
            if board.type == Board.BoardType.Finance:
                res = {'current_board': board }
                return render(request, 'finance/board.html', res)
            else:
                print(f'type: {board.type}| type"s type: {type(board.type)}')
    return JsonResponse({'success': False, 'errorMsg': 'Something went wrong'})

templates/finance/board.html
{% load static %}
<div id="board-component">
    <h1>{{ current_board.caption }}</h1>
    <div id="table" onmousemove="tableHover(event)" onmouseleave="tableLeave()">
        <div id="categories-container"></div>
        <div id="years-container"></div>
    </div>
</div>

templates/finance/categories.html
{% load static %}
<div id="categories-component">
    <div id="categories-column">
        <div class="cell"> </div>
        <div class="cell"> </div>
        {% for category in categories %}
        <div class="clickable cell" onclick="openCategoryForm(this, {{ category.id }}, '{{ category.escaped_caption }}')">
            {{ category.caption }}
        </div>
        {% endfor %}
    </div>

    <div class="clickable cell" onclick="openCategoryForm(this, null, '')">
        <span>Додати категорію /</span>
        <span>Разом</span>
    </div>

    <form id="new-category" method="post"
            class="popup-content hidden" onclick="stopEvent()">
        {% csrf_token %}
        <input id="board_id" type="hidden" name="board_id">
        <input id="category_id" type="hidden" name="id">
        <div>
            <input id="caption" type="text" name="caption" autocomplete="off">
            <img class="btn apply" alt="OK"
                src="{% static 'icons/check.png' %}"
                onclick="send(this, '{% url 'finance:category' %}', loadCategories)"/>
        </div>
    </form>
</div>

templates/finance/year.html
<div id="{{ year }}" class="year-container">
    <div class="expance-column">
        <div class="clickable cell" onclick="expander_hedder_click(this)">
            {{ year }}
        </div>
        <div class="cell">
            Разом
        </div>
        {% for year_cat in year_categories %}
        <div class="clickable cell">
            {{ year_cat.sum }}
        </div>
        {% endfor %}
    </div>
    {% for month in months %}
    <div class="month-container">
        <div class="expance-column">
            <div class="cell"> </div>
            <div class="cell" onclick="expander_hedder_click(this)">
                {{ month.caption }}
            </div>
            {% for month_cat in month.categories %}
            <div class="clickable cell">
                {{ month_cat.sum }}
            </div>
            {% endfor %}
        </div>
        {% for day in month.days %}
        <div class="expander-column">
            <div class="cell"> </div>
            <div class="cell">
                {{ day.caption }}
            </div>
            {% for day_cat in day.categories %}
            <div class="clickable cell">
                {{ day_cat.sum }}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>

templates/general/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}
        <link rel="icon" href="{% static 'icons/mantis.png' %}">
        <link rel="stylesheet" href="{% static 'css/general/base.css' %}">
        <meta name="color-scheme" content="dark">
        <script src="{% static 'js/general/page-helper.js' %}"></script>
        <script src="{% static 'js/general/request-helper.js' %}"></script>
        <script src="{% static 'js/general/board-list.js' %}"></script>
        <script>
            var static_finance_board_js = '{% static "js/finance/board.js" %}';
            var static_finance_board_css = "{% static 'css/finance/board.css' %}";
            var statuc_icon_check = "{% static 'icons/check.png' %}";
            var url_general_board = '{% url "general:board" %}';
            var url_finance_category = '{% url "finance:category" %}';
            var url_finance_year = '{% url "finance:year" %}';

            var debug = {{ debugMode }};
        </script>
    </head>

    <body onclick="deselect()" onload="loadBoardList()">
        <div id="side-bar">
            <div>
                <div id="boards"></div>
                {% if user.is_authenticated %}
                <img class="side-bar-btn" alt="Add"
                    src="{% static 'icons/plus.png' %}"
                    onclick="activateById('new-board')">
                {% endif %}
            </div>
            <div>
                {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" title="Log Out">
                    <img class="side-bar-btn" alt="Exit"
                        src="{% static 'icons/exit.png' %}">
                </a>
                {% else %}
                <a href="{% url 'login' %}" title="{{ user.name }}">
                    <img class="side-bar-btn" alt="LogIn"
                        src="{% static 'icons/login.png' %}">
                </a>
                {% endif %}
                <img class="side-bar-btn" alt="Info"
                    src="{% static 'icons/info.png' %}"
                    onclick="activateById('info')">
            </div>
        </div>
        <div id="info" class="popup-container centered-250 hidden">
            <div class="popup-content">
                <h1>Created by Morik666</h1>
                <p>Source code on: <a href='https://gitlab.com/Morik666/mantis'>GitLab</a></p>
                <p>Icons created by: <a href='https://www.flaticon.com/authors/freepik' title='icons'>Freepik on Flaticon</a></p>
            </div>
        </div>

        {% if user.is_authenticated %}
        <form id="new-board" class="popup-container centered-250 hidden" onclick="stopEvent()">
            {% csrf_token %}
            <input type="hidden" name="id">
            <span id="message" class="hidden"></span>
            <div class="popup-content">
                <h1>Add board</h1>
                <input type="text" name="caption" maxlength="20" placeholder="Caption" autocomplete="off">
                <select name="type">
                    {% for type in board_types %}
                        <option value="{{ type.0 }}">{{ type.1 }}</option>
                    {% endfor %}
                </select><br>
                <img class="btn apply" alt="OK"
                    src="{% static 'icons/check.png' %}"
                    onclick="send(this, '{% url 'general:board' %}', loadBoardList)"/>
                <img class="btn cancel" alt="X"
                    src="{% static 'icons/delete.png' %}"
                    onclick="deselect()"/>
            </div>
        </form>
        {% endif %}
        <div id="main-body">
            <h1>Hello!</h1>
            {% block body %} {% endblock body %}
        </div>
    </body>
</html>

templates/general/board-list.html
{% load static %}
<div>
    {% for board in boards %}
    {# href="{{ board.get_url }}" #}
    <a onclick="loadBoard({{ board.id }})">
        {% if board.type == 0 %}
        <img class="side-bar-btn" alt="Board" title="{{ board.caption }}"
            src="{% static 'icons/list.png' %}">
        {% elif board.type == 1 %}
        <img class="side-bar-btn" alt="Table"
            src="{% static 'icons/dollar.png' %}">
        {% endif %}
    </a>
    {% endfor %}
</div>